---
- hosts: node3
  become: yes
  remote_user: root
  tasks:
  - name: Create a new primary partition with a size of 1GiB
    parted:
      device: /dev/sdb
      number: 1
      state: present
      part_end: 5GiB
  - name: Create a volume group on top of /dev/sdb with physical extent size = 128KiB
    lvg:
      vg: vg_database
      pvs: /dev/sdb1      
      state: present
     # force: yes
  - name: Create a logical volume of 512m with disks /dev/sda and /dev/sdb
    lvol:
      vg: vg_database
      lv: lv_mysql
      size: 512
      state: present
  - name: Create a ext2 filesystem on /dev/sdb1
    filesystem:
      fstype: xfs
      dev: /dev/vg_database/lv_mysql
  - name: Mount up device by UUID
    mount:
      path: /mnt/mysql_backups
      src: /dev/vg_database/lv_mysql
      fstype: xfs
      opts: noatime
      state: present
